### ISSUE TITLE
Installation hurdles

### ISSUE THREAD

**Issue by HaoZeke** [prestsoftware/prest#3]
# Dependencies and over specified defaults
**Acceptance blocker (https://github.com/openjournals/joss-reviews/issues/1015).**

The default installation stalls without `mypy` which is really meant for tests and should be decoupled from the main installation procedure or documented as a requirement.

```bash
make run
```

In fact, as it stands, the `make run` command also builds documentation, which also should be optional.

The error generated by not having `mypy` is:

``` bash
mypy --platform win32 --ignore-missing-imports --check-untyped-defs --strict-optional main.py
make[1]: execvp: mypy: Permission denied
make[1]: *** [Makefile:7: .typecheck-ts] Error 127
make[1]: Leaving directory '/home/haozeke/Git/Github/Reviews/prest/gui'
make: *** [Makefile:16: gui/.typecheck-ts] Error 2
```

# Warnings and Cosmetics

Also, the documentation generation has several warnings of the form:

`/home/haozeke/Git/Github/Reviews/prest/docs/src/references.rst: WARNING: Citation [redelmeier-shafir95] is not referenced.`

If these are not intentional these should be either suppressed or fixed.

In addition to this there are some minor changes which I am adding as pull requests, namely:

- The installation instructions create a `venv` which should be ignored
- The installation instructions differ for the virtual environment case (`pip install -r` instead of `pip install --user -r`

**Comment by ziman** [comment]
Thank you for catching this!

Indeed, `mypy` is a build requirement, which I did not realise. My view is that typechecking is an integral part of the build, and therefore I will add `mypy` to `requirements.txt`.

The documentation is also part of the build — it can be invoked from the GUI so it must be built before you run Prest. For distribution, the whole HTML directory is also embedded in the distribution executable.

We should probably document this as well. Thank you for pointing this out!

**Comment by ziman** [comment]
I also agree that the doc build warnings should be suppressed (we include unreferenced citations intentionally).

**Comment by HaoZeke** [comment]
Thanks for resolving these (warnings can be handled later) in 92c4c9d41e0dcd1a191a6faa377796e8dfa3d75a and f45f6c36ff2b54d08d6a949f9593c47e314127ef!
